# Generated by Django 4.2.21 on 2026-06-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_default_role_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline'), ('ON_LEAVE', 'On leave')], default='AVAILABLE', max_length=20),
        ),
    ]
