# Generated by Django 4.2.21 on 2026-06-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='leads_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broker',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
