"""Notification type codes (docs §12.3)."""


class NotificationCode:
    LEAD_ASSIGNED = "LEAD_ASSIGNED"
    LEAD_REASSIGNED_SLA = "LEAD_REASSIGNED_SLA"
    SLA_WARNING = "SLA_WARNING"
    SLA_BREACHED = "SLA_BREACHED"
    MANUAL_DISTRIBUTION_REQUIRED = "MANUAL_DISTRIBUTION_REQUIRED"
    FOLLOWUP_DUE = "FOLLOWUP_DUE"
    MEETING_DUE = "MEETING_DUE"
    FROZEN_LEAD_RETURN = "FROZEN_LEAD_RETURN"
    STAGE_CHANGED = "STAGE_CHANGED"
    LEAD_REACTIVATED = "LEAD_REACTIVATED"
    WALKIN_WAITING = "WALKIN_WAITING"
    BROKER_LEAD_CREATED = "BROKER_LEAD_CREATED"
    CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
    CAMPAIGN_SUBMITTED_FINANCE = "CAMPAIGN_SUBMITTED_FINANCE"
    CAMPAIGN_APPROVED = "CAMPAIGN_APPROVED"
    CAMPAIGN_SEMI_APPROVED = "CAMPAIGN_SEMI_APPROVED"
    CAMPAIGN_REJECTED = "CAMPAIGN_REJECTED"
    BUDGET_CHANGED = "BUDGET_CHANGED"
    USER_PERMISSION_CHANGED = "USER_PERMISSION_CHANGED"
    WEBHOOK_FAILED = "WEBHOOK_FAILED"
    IMPORT_COMPLETED = "IMPORT_COMPLETED"
    SYSTEM_JOB_FAILED = "SYSTEM_JOB_FAILED"


class Channel:
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    WEBSOCKET = "WEBSOCKET"
