"""Central lead creation (docs §8.1, §8.2, §13). Every source — manual, walk-in,
campaign, webhook — funnels through here so source rules, duplicate handling,
broker-ownership separation, attribution, SLA, audit and distribution stay
consistent (§13 requires webhook leads to use this same service)."""
from __future__ import annotations

from django.db import transaction
from django.utils import timezone

from apps.audit.services import AuditService
from apps.core.constants import AuditAction
from apps.core.exceptions import ValidationError
from apps.notifications.constants import NotificationCode
from apps.notifications.services import NotificationService

from ..constants import ActiveStatus, Origin, SourceCode, StageCode
from ..models import (
    BrokerLeadOwnershipHistory,
    Lead,
    LeadSourceDefinition,
    LeadStageDefinition,
)
from .duplicate_service import DuplicateService
from .sla_service import SLAService


class LeadCreationService:
    @staticmethod
    @transaction.atomic
    def create(
        *,
        company,
        source_code: str,
        name: str,
        phone: str,
        actor=None,
        origin: str = Origin.DIRECT,
        request_meta=None,
        broker_owner=None,
        campaign=None,
        campaign_child_type: str = "",
        campaign_child_id=None,
        language=None,
        assigned_salesman=None,
        assigned_team=None,
        call_center_agent=None,
        auto_distribute: bool = True,
        metadata: dict | None = None,
        attribution_platform=None,
        attribution_event=None,
        **extra,
    ) -> Lead:
        print(f"\n[LeadCreationService] create called: source={source_code}, name={name}, phone={phone}, salesman={assigned_salesman}, team={assigned_team}, auto={auto_distribute}")
        if not name or not phone:
            raise ValidationError("Lead requires name and phone (docs §8.1).")

        source = LeadSourceDefinition.objects.get(code=source_code, is_active=True)
        LeadCreationService._validate_source(
            source, broker_owner=broker_owner, campaign=campaign,
            assigned_salesman=assigned_salesman, **extra,
        )

        # Self-generated by a salesman auto-assigns to that salesman (leads spec
        # §4.2a). Keep-vs-redistribute-after-SLA is governed by policy at SLA time.
        if (source_code == SourceCode.SELF_GENERATED and assigned_salesman is None
                and actor is not None
                and actor.team_memberships.filter(team__company=company).exists()):
            assigned_salesman = actor
            auto_distribute = False

        # Existing client: check if prior salesman is active and preserve if policy is set.
        if source_code == SourceCode.EXISTING_CLIENT and assigned_salesman is None:
            from apps.policies.constants import PolicyCode
            from apps.policies.services import PolicyResolver
            from apps.leads.models import Client

            policy = PolicyResolver.option_code(
                company, PolicyCode.EXISTING_CLIENT_POLICY, default="PRESERVE_PRIOR_RELATIONSHIP"
            )
            if policy == "PRESERVE_PRIOR_RELATIONSHIP":
                prior = (
                    Client.objects.filter(company=company, phone=phone)
                    .select_related("original_salesman")
                    .first()
                )
                if prior and prior.original_salesman and prior.original_salesman.is_active:
                    assigned_salesman = prior.original_salesman
                    auto_distribute = False

        dup = DuplicateService.check(company=company, phone=phone)
        print(f"[LeadCreationService] Duplicate check completed. requires_manual={dup.requires_manual}, existing={dup.existing}")
        # Active + in-SLA duplicate => manual escalation, never auto (docs §8.1).
        if dup.requires_manual:
            LeadCreationService._escalate_manual(company, dup.existing, actor)
            return dup.existing

        fresh = LeadStageDefinition.objects.get(code=StageCode.FRESH)
        lead = Lead.objects.create(
            company=company,
            source=source,
            name=name,
            phone=phone,
            email=extra.get("email", ""),
            country_code=extra.get("country_code", ""),
            origin=origin,
            language=language,
            broker_owner=broker_owner,
            campaign=campaign,
            campaign_child_type=campaign_child_type,
            campaign_child_id=campaign_child_id,
            assigned_team=assigned_team,
            assigned_salesman=assigned_salesman,
            call_center_agent=call_center_agent,
            current_stage=fresh,
            active_status=ActiveStatus.ACTIVE,
            created_by=actor,
            last_activity_at=timezone.now(),
            metadata=metadata,
        )
        print(f"[LeadCreationService] Lead object created in DB: id={lead.id}, name={lead.name}")

        if broker_owner is not None:
            BrokerLeadOwnershipHistory.objects.create(
                lead=lead, broker=broker_owner, action="CREATED",
                new_broker=broker_owner, actor=actor,
            )
            broker_owner.leads_count += 1
            broker_owner.save(update_fields=["leads_count", "updated_at"])
            NotificationService.create_for_users(
                company=company, recipients=[broker_owner.linked_user],
                code=NotificationCode.BROKER_LEAD_CREATED,
                related_type="Lead", related_id=lead.pk,
            )

        # Attribution into campaign children (docs §10.5) when campaign present.
        if campaign is not None:
            LeadCreationService._attribute(
                lead, platform=attribution_platform, event=attribution_event
            )

        AuditService.log(
            action=AuditAction.CREATE, instance=lead, actor=actor,
            company=company, module="leads", request_meta=request_meta,
            after={"name": name, "phone": phone, "source": source_code},
        )

        # Distribution decision is owned by the distribution engine (docs §8.3).
        if assigned_salesman is not None:
            deadline = SLAService.calculate_deadline(
                company, stage_code=StageCode.FRESH, origin=origin, source_code=source_code
            )
            SLAService.open_instance(lead=lead, stage=fresh, deadline=deadline)
            lead.sla_deadline = deadline
            lead.save(update_fields=["sla_deadline", "updated_at"])
            NotificationService.lead_assigned(company, lead, assigned_salesman)
        elif auto_distribute and source_code != SourceCode.EXHIBITION:
            LeadCreationService._dispatch_distribution(lead, actor, request_meta)
        else:
            LeadCreationService._escalate_manual(company, lead, actor)

        print(f"[LeadCreationService] Lead creation workflow finished: lead_id={lead.id}, assigned_salesman={lead.assigned_salesman}, assigned_team={lead.assigned_team}\n")
        return lead

    @staticmethod
    def _validate_source(source, *, broker_owner, campaign, assigned_salesman, **extra):
        if source.requires_broker and broker_owner is None:
            raise ValidationError("Broker required for this source (docs §8.2).")
        if source.requires_campaign and campaign is None:
            raise ValidationError("Campaign required for this source (docs §8.2).")
        if source.requires_salesman and assigned_salesman is None:
            raise ValidationError(
                "Salesman must be selected for this source (docs §8.2)."
            )
        if source.requires_referrer and not extra.get("referrer_name"):
            raise ValidationError("Referrer name required (docs §8.2).")

    @staticmethod
    def _dispatch_distribution(lead, actor, request_meta):
        # Lazy import avoids a leads<->distribution import cycle.
        from apps.distribution.services import DistributionEngine

        DistributionEngine.distribute(lead=lead, actor=actor, request_meta=request_meta)

    @staticmethod
    def _escalate_manual(company, lead, actor):
        from apps.distribution.services import ManualDistributionEscalation

        ManualDistributionEscalation.notify(company=company, lead=lead, actor=actor)

    @staticmethod
    def _attribute(lead, platform=None, event=None):
        from apps.marketing.services.campaign_attribution_service import (
            CampaignAttributionService,
        )

        CampaignAttributionService.link_lead(
            lead=lead, platform=platform, event=event
        )
