# Generated by Django 4.2.21 on 2026-06-25 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0003_howdidyouknowoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_center_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_agent_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
