# Generated by Django 4.2.21 on 2026-06-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_call_center_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='slainstance',
            name='expiry_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
