# Generated by Django 4.2.21 on 2026-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_slainstance_expiry_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slainstance',
            name='reminder_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
