# Generated by Django 4.2.21 on 2026-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_slainstance_reminder_task_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_salesman', 'status', 'scheduled_at'], name='leads_follo_assigne_0e37e4_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead', 'status', 'scheduled_at'], name='leads_follo_lead_id_45bbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['assigned_salesman', 'status', 'scheduled_start'], name='leads_meeti_assigne_7f0f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['lead', 'status', 'scheduled_start'], name='leads_meeti_lead_id_be1a31_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['lead', 'reminder_type', 'status'], name='leads_remin_lead_id_7c81b8_idx'),
        ),
    ]
