# Generated by Django 4.2.21 on 2026-06-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company display name', max_length=255)),
                ('slug', models.SlugField(help_text="URL segment and DB key, e.g. 'acme' -> /t/acme/", max_length=63, unique=True)),
                ('db_name', models.CharField(max_length=64)),
                ('db_host', models.CharField(default='127.0.0.1', max_length=255)),
                ('db_port', models.CharField(default='3306', max_length=8)),
                ('db_user', models.CharField(default='root', max_length=64)),
                ('db_password', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to suspend access; data is preserved.')),
                ('paid_until', models.DateField(blank=True, help_text='Optional: when the current paid period ends.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
