# Generated by Django 4.2.21 on 2026-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_socialmediaadrecord_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='lead_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitionrecord',
            name='lead_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmediaadrecord',
            name='lead_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streetadrecord',
            name='lead_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvadrecord',
            name='lead_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
