# Generated by Django 4.2.21 on 2026-06-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_eventrecord_lead_count_exhibitionrecord_lead_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='rejected_budgets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
