# Generated by Django 4.2.21 on 2026-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_campaign_rejected_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='actual_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
