# Generated by Django 4.2.21 on 2026-06-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('OPTION', 'Option'), ('DURATION', 'Duration'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('CODE', 'Code')], default='OPTION', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('class_path', models.CharField(max_length=255)),
                ('module', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('value_type', models.CharField(choices=[('OPTION', 'Option'), ('DURATION', 'Duration'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('CODE', 'Code')], default='JSON', max_length=20)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('company_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='policies.companypolicyvalue')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyOptionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('strategy_code', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='policies.policydefinition')),
            ],
        ),
        migrations.AddField(
            model_name='companypolicyvalue',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_values', to='policies.policydefinition'),
        ),
        migrations.AddField(
            model_name='companypolicyvalue',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.policyoptiondefinition'),
        ),
        migrations.AddField(
            model_name='companypolicyvalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='policyparameter',
            constraint=models.UniqueConstraint(fields=('company_policy', 'key'), name='uniq_policy_parameter'),
        ),
        migrations.AddConstraint(
            model_name='policyoptiondefinition',
            constraint=models.UniqueConstraint(fields=('policy', 'code'), name='uniq_policy_option_code'),
        ),
        migrations.AddConstraint(
            model_name='companypolicyvalue',
            constraint=models.UniqueConstraint(fields=('company', 'policy'), name='uniq_company_policy'),
        ),
    ]
