# Generated by Django 4.2.21 on 2026-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydefinition',
            name='value_type',
            field=models.CharField(choices=[('OPTION', 'Option'), ('DURATION', 'Duration'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('CODE', 'Code'), ('COMPOSITE', 'Composite')], default='OPTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='policyparameter',
            name='value_type',
            field=models.CharField(choices=[('OPTION', 'Option'), ('DURATION', 'Duration'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('CODE', 'Code'), ('COMPOSITE', 'Composite')], default='JSON', max_length=20),
        ),
    ]
