# Generated by Django 4.2.21 on 2026-06-24 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=150)),
                ('task_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['task_name', 'status'], name='audit_jobex_task_na_e3e410_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_code', models.CharField(max_length=120)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('STAGE_CHANGE', 'Stage change'), ('SLA_EVENT', 'SLA event'), ('APPROVE', 'Approve'), ('PERMISSION_CHANGE', 'Permission change'), ('POLICY_CHANGE', 'Policy change'), ('BUDGET_CHANGE', 'Budget change'), ('WEBHOOK_EVENT', 'Webhook event'), ('JOB_RESULT', 'Job result'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('LOGIN', 'Login')], max_length=40)),
                ('module', models.CharField(blank=True, max_length=60)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(max_length=64)),
                ('entity_display', models.CharField(blank=True, max_length=255)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('request_meta', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEventField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=120)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('old_display', models.TextField(blank=True)),
                ('new_display', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='audit.auditlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'entity_type', 'entity_id'], name='audit_audit_company_d8ad9e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'),
        ),
    ]
