# Generated by Django 4.2.21 on 2026-06-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOutbox',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
